#!/usr/bin/env python3
"""
Script to generate 60 additional Korean meals (meal_id 41-100)
"""

meals = [
    # 41-50: 고기/단백질
    {
        "meal_id": "41",
        "name": "농심 소고기 미역국",
        "brand": "농심",
        "category": "즉석국",
        "ingredients": ["소고기", "미역", "다시마", "마늘"],
        "allergens": ["beef", "soy"],
        "calories": 180,
        "protein_g": 12,
        "carbs_g": 18,
        "fat_g": 6,
        "sodium_mg": 890,
        "serving_size": "1봉(500ml)",
        "origin": "국내산 미역",
        "score": 78
    },
    {
        "meal_id": "42",
        "name": "CJ 고메 안심 스테이크",
        "brand": "CJ제일제당",
        "category": "냉동육류",
        "ingredients": ["소고기안심", "올리브유", "로즈마리", "마늘"],
        "allergens": ["beef"],
        "calories": 280,
        "protein_g": 32,
        "carbs_g": 2,
        "fat_g": 16,
        "sodium_mg": 420,
        "serving_size": "150g",
        "origin": "호주산",
        "score": 88
    },
    {
        "meal_id": "43",
        "name": "동원 돼지고기 두루치기",
        "brand": "동원F&B",
        "category": "즉석조리",
        "ingredients": ["돼지고기", "양파", "고추장", "마늘"],
        "allergens": ["pork", "soy"],
        "calories": 320,
        "protein_g": 22,
        "carbs_g": 15,
        "fat_g": 18,
        "sodium_mg": 950,
        "serving_size": "200g",
        "origin": "국내산 돼지고기",
        "score": 75
    },
    {
        "meal_id": "44",
        "name": "풀무원 삼계탕",
        "brand": "풀무원",
        "category": "즉석국",
        "ingredients": ["닭고기", "인삼", "대추", "마늘", "찹쌀"],
        "allergens": ["chicken"],
        "calories": 380,
        "protein_g": 28,
        "carbs_g": 25,
        "fat_g": 16,
        "sodium_mg": 780,
        "serving_size": "800g",
        "origin": "국내산 닭고기",
        "score": 82
    },
    {
        "meal_id": "45",
        "name": "동원 화이트 참치살코기",
        "brand": "동원F&B",
        "category": "통조림",
        "ingredients": ["참치", "정제수", "소금"],
        "allergens": ["fish"],
        "calories": 110,
        "protein_g": 26,
        "carbs_g": 0,
        "fat_g": 1,
        "sodium_mg": 320,
        "serving_size": "100g",
        "origin": "태국산",
        "score": 92
    },
    {
        "meal_id": "46",
        "name": "사조 살코기 고등어",
        "brand": "사조대림",
        "category": "통조림",
        "ingredients": ["고등어", "정제수"],
        "allergens": ["fish"],
        "calories": 190,
        "protein_g": 22,
        "carbs_g": 0,
        "fat_g": 12,
        "sodium_mg": 280,
        "serving_size": "120g",
        "origin": "노르웨이산",
        "score": 86
    },
    {
        "meal_id": "47",
        "name": "CJ 비비고 LA 갈비",
        "brand": "CJ제일제당",
        "category": "냉동육류",
        "ingredients": ["소갈비", "간장", "배", "마늘", "설탕"],
        "allergens": ["beef", "soy"],
        "calories": 420,
        "protein_g": 26,
        "carbs_g": 18,
        "fat_g": 28,
        "sodium_mg": 980,
        "serving_size": "200g",
        "origin": "미국산",
        "score": 70
    },
    {
        "meal_id": "48",
        "name": "하림 닭가슴살 소시지",
        "brand": "하림",
        "category": "육가공",
        "ingredients": ["닭가슴살", "치즈", "양파"],
        "allergens": ["chicken", "milk"],
        "calories": 140,
        "protein_g": 18,
        "carbs_g": 6,
        "fat_g": 4,
        "sodium_mg": 480,
        "serving_size": "80g",
        "origin": "국내산 닭고기",
        "score": 83
    },
    {
        "meal_id": "49",
        "name": "동원 연어 스테이크",
        "brand": "동원F&B",
        "category": "냉동수산",
        "ingredients": ["연어", "레몬", "딜"],
        "allergens": ["fish"],
        "calories": 240,
        "protein_g": 28,
        "carbs_g": 0,
        "fat_g": 14,
        "sodium_mg": 220,
        "serving_size": "120g",
        "origin": "노르웨이산",
        "score": 90
    },
    {
        "meal_id": "50",
        "name": "풀무원 탄탄 두부",
        "brand": "풀무원",
        "category": "두부",
        "ingredients": ["대두", "간수"],
        "allergens": ["soy"],
        "calories": 90,
        "protein_g": 10,
        "carbs_g": 3,
        "fat_g": 5,
        "sodium_mg": 15,
        "serving_size": "150g",
        "origin": "국내산 콩",
        "score": 88
    },

    # 51-60: 밥/곡물
    {
        "meal_id": "51",
        "name": "CJ 햇반 현미밥",
        "brand": "CJ제일제당",
        "category": "즉석밥",
        "ingredients": ["현미", "물"],
        "allergens": [],
        "calories": 310,
        "protein_g": 7,
        "carbs_g": 68,
        "fat_g": 2,
        "sodium_mg": 5,
        "serving_size": "210g",
        "origin": "국내산 쌀",
        "score": 85
    },
    {
        "meal_id": "52",
        "name": "풀무원 귀리밥",
        "brand": "풀무원",
        "category": "즉석밥",
        "ingredients": ["귀리", "쌀", "보리"],
        "allergens": ["wheat"],
        "calories": 280,
        "protein_g": 9,
        "carbs_g": 58,
        "fat_g": 3,
        "sodium_mg": 8,
        "serving_size": "210g",
        "origin": "국내산",
        "score": 87
    },
    {
        "meal_id": "53",
        "name": "오뚜기 잡곡밥",
        "brand": "오뚜기",
        "category": "즉석밥",
        "ingredients": ["현미", "귀리", "보리", "렌틸콩"],
        "allergens": ["wheat"],
        "calories": 290,
        "protein_g": 8,
        "carbs_g": 62,
        "fat_g": 2,
        "sodium_mg": 10,
        "serving_size": "210g",
        "origin": "국내산",
        "score": 86
    },
    {
        "meal_id": "54",
        "name": "CJ 컵반 소고기 덮밥",
        "brand": "CJ제일제당",
        "category": "즉석밥",
        "ingredients": ["쌀", "소고기", "양파", "간장"],
        "allergens": ["beef", "soy", "wheat"],
        "calories": 450,
        "protein_g": 16,
        "carbs_g": 72,
        "fat_g": 10,
        "sodium_mg": 920,
        "serving_size": "280g",
        "origin": "국내산 쌀",
        "score": 72
    },
    {
        "meal_id": "55",
        "name": "농심 신라면볶음밥",
        "brand": "농심",
        "category": "즉석밥",
        "ingredients": ["쌀", "신라면스프", "김치", "야채"],
        "allergens": ["soy", "wheat"],
        "calories": 520,
        "protein_g": 12,
        "carbs_g": 85,
        "fat_g": 14,
        "sodium_mg": 1280,
        "serving_size": "280g",
        "origin": "국내산",
        "score": 65
    },
    {
        "meal_id": "56",
        "name": "오뚜기 진밥 곤약밥",
        "brand": "오뚜기",
        "category": "즉석밥",
        "ingredients": ["곤약", "쌀", "현미"],
        "allergens": [],
        "calories": 180,
        "protein_g": 4,
        "carbs_g": 42,
        "fat_g": 1,
        "sodium_mg": 12,
        "serving_size": "210g",
        "origin": "국내산",
        "score": 90
    },
    {
        "meal_id": "57",
        "name": "CJ 햇반 흑미밥",
        "brand": "CJ제일제당",
        "category": "즉석밥",
        "ingredients": ["흑미", "쌀"],
        "allergens": [],
        "calories": 300,
        "protein_g": 7,
        "carbs_g": 66,
        "fat_g": 2,
        "sodium_mg": 6,
        "serving_size": "210g",
        "origin": "국내산",
        "score": 84
    },
    {
        "meal_id": "58",
        "name": "풀무원 쁘띠첼 단호박죽",
        "brand": "풀무원",
        "category": "죽",
        "ingredients": ["단호박", "쌀", "우유"],
        "allergens": ["milk"],
        "calories": 220,
        "protein_g": 5,
        "carbs_g": 42,
        "fat_g": 4,
        "sodium_mg": 180,
        "serving_size": "280g",
        "origin": "국내산 단호박",
        "score": 80
    },
    {
        "meal_id": "59",
        "name": "본죽 전복죽",
        "brand": "본아이에프",
        "category": "죽",
        "ingredients": ["쌀", "전복", "참기름", "야채"],
        "allergens": ["shellfish", "sesame"],
        "calories": 280,
        "protein_g": 8,
        "carbs_g": 48,
        "fat_g": 6,
        "sodium_mg": 680,
        "serving_size": "350g",
        "origin": "국내산 전복",
        "score": 76
    },
    {
        "meal_id": "60",
        "name": "오뚜기 맛있는 오트밀 플레인",
        "brand": "오뚜기",
        "category": "시리얼",
        "ingredients": ["귀리"],
        "allergens": ["wheat"],
        "calories": 380,
        "protein_g": 14,
        "carbs_g": 68,
        "fat_g": 7,
        "sodium_mg": 5,
        "serving_size": "100g",
        "origin": "호주산",
        "score": 89
    },

    # 61-70: 샐러드/야채
    {
        "meal_id": "61",
        "name": "풀무원 닭가슴살 샐러드",
        "brand": "풀무원",
        "category": "샐러드",
        "ingredients": ["닭가슴살", "양상추", "방울토마토", "드레싱"],
        "allergens": ["chicken", "eggs"],
        "calories": 180,
        "protein_g": 22,
        "carbs_g": 12,
        "fat_g": 5,
        "sodium_mg": 420,
        "serving_size": "200g",
        "origin": "국내산",
        "score": 88
    },
    {
        "meal_id": "62",
        "name": "GS25 그릴드 치킨 샐러드",
        "brand": "GS리테일",
        "category": "샐러드",
        "ingredients": ["닭가슴살", "케일", "퀴노아", "견과류"],
        "allergens": ["chicken", "tree nuts"],
        "calories": 250,
        "protein_g": 24,
        "carbs_g": 18,
        "fat_g": 8,
        "sodium_mg": 480,
        "serving_size": "250g",
        "origin": "국내산",
        "score": 86
    },
    {
        "meal_id": "63",
        "name": "CU 단백질 샐러드",
        "brand": "BGF리테일",
        "category": "샐러드",
        "ingredients": ["계란", "두부", "브로콜리", "아보카도"],
        "allergens": ["eggs", "soy"],
        "calories": 220,
        "protein_g": 18,
        "carbs_g": 14,
        "fat_g": 10,
        "sodium_mg": 380,
        "serving_size": "230g",
        "origin": "국내산",
        "score": 87
    },
    {
        "meal_id": "64",
        "name": "풀무원 그린주스 시금치",
        "brand": "풀무원",
        "category": "음료",
        "ingredients": ["시금치", "바나나", "사과", "레몬"],
        "allergens": [],
        "calories": 95,
        "protein_g": 2,
        "carbs_g": 22,
        "fat_g": 0,
        "sodium_mg": 45,
        "serving_size": "200ml",
        "origin": "국내산 시금치",
        "score": 82
    },
    {
        "meal_id": "65",
        "name": "동원 양배추 쌈",
        "brand": "동원F&B",
        "category": "즉석식품",
        "ingredients": ["양배추", "돼지고기", "두부", "된장"],
        "allergens": ["pork", "soy"],
        "calories": 280,
        "protein_g": 16,
        "carbs_g": 22,
        "fat_g": 14,
        "sodium_mg": 780,
        "serving_size": "300g",
        "origin": "국내산",
        "score": 76
    },
    {
        "meal_id": "66",
        "name": "풀무원 브로콜리 샐러드",
        "brand": "풀무원",
        "category": "샐러드",
        "ingredients": ["브로콜리", "퀴노아", "크랜베리", "호두"],
        "allergens": ["tree nuts"],
        "calories": 160,
        "protein_g": 6,
        "carbs_g": 20,
        "fat_g": 7,
        "sodium_mg": 220,
        "serving_size": "180g",
        "origin": "국내산",
        "score": 85
    },
    {
        "meal_id": "67",
        "name": "오뚜기 단무지",
        "brand": "오뚜기",
        "category": "반찬",
        "ingredients": ["무", "설탕", "식초", "소금"],
        "allergens": [],
        "calories": 45,
        "protein_g": 1,
        "carbs_g": 10,
        "fat_g": 0,
        "sodium_mg": 680,
        "serving_size": "100g",
        "origin": "국내산 무",
        "score": 70
    },
    {
        "meal_id": "68",
        "name": "CJ 비비고 나물 3종 세트",
        "brand": "CJ제일제당",
        "category": "반찬",
        "ingredients": ["시금치", "콩나물", "고사리", "참기름"],
        "allergens": ["sesame", "soy"],
        "calories": 120,
        "protein_g": 5,
        "carbs_g": 12,
        "fat_g": 6,
        "sodium_mg": 420,
        "serving_size": "150g",
        "origin": "국내산",
        "score": 82
    },
    {
        "meal_id": "69",
        "name": "풀무원 단호박 샐러드",
        "brand": "풀무원",
        "category": "샐러드",
        "ingredients": ["단호박", "그릭요거트", "견과류", "건포도"],
        "allergens": ["milk", "tree nuts"],
        "calories": 200,
        "protein_g": 6,
        "carbs_g": 28,
        "fat_g": 8,
        "sodium_mg": 120,
        "serving_size": "200g",
        "origin": "국내산 단호박",
        "score": 80
    },
    {
        "meal_id": "70",
        "name": "농협 새싹 채소 믹스",
        "brand": "농협",
        "category": "야채",
        "ingredients": ["새싹채소", "브로콜리싹", "무순"],
        "allergens": [],
        "calories": 25,
        "protein_g": 2,
        "carbs_g": 4,
        "fat_g": 0,
        "sodium_mg": 15,
        "serving_size": "80g",
        "origin": "국내산",
        "score": 90
    },

    # 71-80: 김치/발효식품
    {
        "meal_id": "71",
        "name": "CJ 종가집 포기김치",
        "brand": "CJ제일제당",
        "category": "김치",
        "ingredients": ["배추", "무", "고춧가루", "마늘", "젓갈"],
        "allergens": ["fish", "shellfish"],
        "calories": 25,
        "protein_g": 2,
        "carbs_g": 4,
        "fat_g": 0,
        "sodium_mg": 580,
        "serving_size": "100g",
        "origin": "국내산 배추",
        "score": 78
    },
    {
        "meal_id": "72",
        "name": "풀무원 얇은 김치",
        "brand": "풀무원",
        "category": "김치",
        "ingredients": ["배추", "무", "고춧가루", "마늘"],
        "allergens": ["fish"],
        "calories": 20,
        "protein_g": 2,
        "carbs_g": 3,
        "fat_g": 0,
        "sodium_mg": 520,
        "serving_size": "100g",
        "origin": "국내산 배추",
        "score": 80
    },
    {
        "meal_id": "73",
        "name": "CJ 종가집 백김치",
        "brand": "CJ제일제당",
        "category": "김치",
        "ingredients": ["배추", "무", "배", "마늘"],
        "allergens": [],
        "calories": 18,
        "protein_g": 1,
        "carbs_g": 4,
        "fat_g": 0,
        "sodium_mg": 480,
        "serving_size": "100g",
        "origin": "국내산",
        "score": 82
    },
    {
        "meal_id": "74",
        "name": "오뚜기 깍두기",
        "brand": "오뚜기",
        "category": "김치",
        "ingredients": ["무", "고춧가루", "마늘", "젓갈"],
        "allergens": ["fish"],
        "calories": 28,
        "protein_g": 2,
        "carbs_g": 5,
        "fat_g": 0,
        "sodium_mg": 620,
        "serving_size": "100g",
        "origin": "국내산 무",
        "score": 76
    },
    {
        "meal_id": "75",
        "name": "CJ 비비고 총각김치",
        "brand": "CJ제일제당",
        "category": "김치",
        "ingredients": ["총각무", "고춧가루", "마늘"],
        "allergens": ["fish"],
        "calories": 22,
        "protein_g": 2,
        "carbs_g": 4,
        "fat_g": 0,
        "sodium_mg": 560,
        "serving_size": "100g",
        "origin": "국내산",
        "score": 77
    },
    {
        "meal_id": "76",
        "name": "풀무원 오이소박이",
        "brand": "풀무원",
        "category": "김치",
        "ingredients": ["오이", "고춧가루", "마늘", "부추"],
        "allergens": ["fish"],
        "calories": 15,
        "protein_g": 1,
        "carbs_g": 3,
        "fat_g": 0,
        "sodium_mg": 420,
        "serving_size": "100g",
        "origin": "국내산 오이",
        "score": 80
    },
    {
        "meal_id": "77",
        "name": "CJ 햇반 낫또",
        "brand": "CJ제일제당",
        "category": "발효식품",
        "ingredients": ["대두", "낫또균"],
        "allergens": ["soy"],
        "calories": 90,
        "protein_g": 8,
        "carbs_g": 6,
        "fat_g": 5,
        "sodium_mg": 15,
        "serving_size": "50g",
        "origin": "국내산 콩",
        "score": 88
    },
    {
        "meal_id": "78",
        "name": "풀무원 청국장",
        "brand": "풀무원",
        "category": "발효식품",
        "ingredients": ["대두", "청국장균", "파", "마늘"],
        "allergens": ["soy"],
        "calories": 110,
        "protein_g": 10,
        "carbs_g": 8,
        "fat_g": 5,
        "sodium_mg": 680,
        "serving_size": "80g",
        "origin": "국내산 콩",
        "score": 82
    },
    {
        "meal_id": "79",
        "name": "서울우유 케피어",
        "brand": "서울우유",
        "category": "발효유",
        "ingredients": ["우유", "케피어균"],
        "allergens": ["milk"],
        "calories": 75,
        "protein_g": 4,
        "carbs_g": 9,
        "fat_g": 2,
        "sodium_mg": 55,
        "serving_size": "150ml",
        "origin": "국내산 우유",
        "score": 84
    },
    {
        "meal_id": "80",
        "name": "빙그레 떠먹는 불가리스",
        "brand": "빙그레",
        "category": "발효유",
        "ingredients": ["우유", "유산균", "과일"],
        "allergens": ["milk"],
        "calories": 85,
        "protein_g": 4,
        "carbs_g": 12,
        "fat_g": 2,
        "sodium_mg": 60,
        "serving_size": "85g",
        "origin": "국내산 우유",
        "score": 82
    },

    # 81-90: 스낵/견과류
    {
        "meal_id": "81",
        "name": "농심 구운 아몬드",
        "brand": "농심",
        "category": "견과류",
        "ingredients": ["아몬드", "소금"],
        "allergens": ["tree nuts"],
        "calories": 580,
        "protein_g": 21,
        "carbs_g": 22,
        "fat_g": 50,
        "sodium_mg": 280,
        "serving_size": "100g",
        "origin": "미국산",
        "score": 86
    },
    {
        "meal_id": "82",
        "name": "롯데 호두과자 미니",
        "brand": "롯데제과",
        "category": "스낵",
        "ingredients": ["밀가루", "호두", "설탕", "계란"],
        "allergens": ["wheat", "tree nuts", "eggs", "milk"],
        "calories": 450,
        "protein_g": 8,
        "carbs_g": 58,
        "fat_g": 22,
        "sodium_mg": 320,
        "serving_size": "100g",
        "origin": "국내산",
        "score": 65
    },
    {
        "meal_id": "83",
        "name": "크라운 쌀과자",
        "brand": "크라운제과",
        "category": "스낵",
        "ingredients": ["쌀", "식물성유지"],
        "allergens": [],
        "calories": 480,
        "protein_g": 6,
        "carbs_g": 68,
        "fat_g": 20,
        "sodium_mg": 420,
        "serving_size": "100g",
        "origin": "국내산 쌀",
        "score": 68
    },
    {
        "meal_id": "84",
        "name": "오리온 닥터유 현미칩",
        "brand": "오리온",
        "category": "스낵",
        "ingredients": ["현미", "올리브유", "소금"],
        "allergens": [],
        "calories": 420,
        "protein_g": 7,
        "carbs_g": 62,
        "fat_g": 16,
        "sodium_mg": 380,
        "serving_size": "100g",
        "origin": "국내산 현미",
        "score": 72
    },
    {
        "meal_id": "85",
        "name": "해태 구운 캐슈넛",
        "brand": "해태제과",
        "category": "견과류",
        "ingredients": ["캐슈넛", "소금"],
        "allergens": ["tree nuts"],
        "calories": 570,
        "protein_g": 18,
        "carbs_g": 32,
        "fat_g": 44,
        "sodium_mg": 320,
        "serving_size": "100g",
        "origin": "베트남산",
        "score": 82
    },
    {
        "meal_id": "86",
        "name": "농심 견과류 믹스",
        "brand": "농심",
        "category": "견과류",
        "ingredients": ["아몬드", "호두", "캐슈넛", "건포도"],
        "allergens": ["tree nuts"],
        "calories": 550,
        "protein_g": 19,
        "carbs_g": 28,
        "fat_g": 45,
        "sodium_mg": 180,
        "serving_size": "100g",
        "origin": "미국산",
        "score": 85
    },
    {
        "meal_id": "87",
        "name": "풀무원 프로틴바 초코",
        "brand": "풀무원",
        "category": "영양바",
        "ingredients": ["대두단백", "귀리", "다크초콜릿"],
        "allergens": ["soy", "milk", "wheat"],
        "calories": 180,
        "protein_g": 15,
        "carbs_g": 18,
        "fat_g": 6,
        "sodium_mg": 120,
        "serving_size": "45g",
        "origin": "국내산",
        "score": 84
    },
    {
        "meal_id": "88",
        "name": "CJ 프로틴 에너지바",
        "brand": "CJ제일제당",
        "category": "영양바",
        "ingredients": ["대두단백", "견과류", "꿀"],
        "allergens": ["soy", "tree nuts"],
        "calories": 190,
        "protein_g": 16,
        "carbs_g": 20,
        "fat_g": 7,
        "sodium_mg": 100,
        "serving_size": "50g",
        "origin": "국내산",
        "score": 83
    },
    {
        "meal_id": "89",
        "name": "해태 맛동산 구운 양파",
        "brand": "해태제과",
        "category": "스낵",
        "ingredients": ["밀가루", "양파", "식물성유지"],
        "allergens": ["wheat"],
        "calories": 510,
        "protein_g": 7,
        "carbs_g": 64,
        "fat_g": 25,
        "sodium_mg": 520,
        "serving_size": "100g",
        "origin": "국내산",
        "score": 62
    },
    {
        "meal_id": "90",
        "name": "오리온 참 곡물 칩",
        "brand": "오리온",
        "category": "스낵",
        "ingredients": ["귀리", "현미", "퀴노아"],
        "allergens": ["wheat"],
        "calories": 440,
        "protein_g": 9,
        "carbs_g": 60,
        "fat_g": 18,
        "sodium_mg": 380,
        "serving_size": "100g",
        "origin": "국내산",
        "score": 74
    },

    # 91-100: 음료/디저트
    {
        "meal_id": "91",
        "name": "매일 소화가 잘되는 우유",
        "brand": "매일유업",
        "category": "유제품",
        "ingredients": ["우유", "유당분해효소"],
        "allergens": ["milk"],
        "calories": 130,
        "protein_g": 6,
        "carbs_g": 11,
        "fat_g": 7,
        "sodium_mg": 100,
        "serving_size": "200ml",
        "origin": "국내산 우유",
        "score": 83
    },
    {
        "meal_id": "92",
        "name": "서울우유 저지방 우유",
        "brand": "서울우유",
        "category": "유제품",
        "ingredients": ["우유"],
        "allergens": ["milk"],
        "calories": 90,
        "protein_g": 6,
        "carbs_g": 11,
        "fat_g": 2,
        "sodium_mg": 110,
        "serving_size": "200ml",
        "origin": "국내산 우유",
        "score": 86
    },
    {
        "meal_id": "93",
        "name": "남양 맛있는 우유GT",
        "brand": "남양유업",
        "category": "유제품",
        "ingredients": ["우유", "비타민D"],
        "allergens": ["milk"],
        "calories": 120,
        "protein_g": 6,
        "carbs_g": 10,
        "fat_g": 6,
        "sodium_mg": 105,
        "serving_size": "200ml",
        "origin": "국내산 우유",
        "score": 84
    },
    {
        "meal_id": "94",
        "name": "풀무원 ABC 주스",
        "brand": "풀무원",
        "category": "음료",
        "ingredients": ["사과", "비트", "당근"],
        "allergens": [],
        "calories": 110,
        "protein_g": 1,
        "carbs_g": 26,
        "fat_g": 0,
        "sodium_mg": 65,
        "serving_size": "200ml",
        "origin": "국내산",
        "score": 78
    },
    {
        "meal_id": "95",
        "name": "농협 바나나우유",
        "brand": "농협",
        "category": "음료",
        "ingredients": ["우유", "바나나", "설탕"],
        "allergens": ["milk"],
        "calories": 180,
        "protein_g": 5,
        "carbs_g": 32,
        "fat_g": 4,
        "sodium_mg": 90,
        "serving_size": "240ml",
        "origin": "국내산 우유",
        "score": 70
    },
    {
        "meal_id": "96",
        "name": "빙그레 바나나맛우유 라이트",
        "brand": "빙그레",
        "category": "음료",
        "ingredients": ["저지방우유", "바나나향", "설탕"],
        "allergens": ["milk"],
        "calories": 120,
        "protein_g": 5,
        "carbs_g": 20,
        "fat_g": 2,
        "sodium_mg": 85,
        "serving_size": "200ml",
        "origin": "국내산 우유",
        "score": 75
    },
    {
        "meal_id": "97",
        "name": "매일 아몬드 브리즈",
        "brand": "매일유업",
        "category": "음료",
        "ingredients": ["아몬드", "물", "칼슘"],
        "allergens": ["tree nuts"],
        "calories": 40,
        "protein_g": 1,
        "carbs_g": 8,
        "fat_g": 1,
        "sodium_mg": 120,
        "serving_size": "200ml",
        "origin": "미국산 아몬드",
        "score": 80
    },
    {
        "meal_id": "98",
        "name": "풀무원 그린주스 케일",
        "brand": "풀무원",
        "category": "음료",
        "ingredients": ["케일", "사과", "레몬", "바나나"],
        "allergens": [],
        "calories": 100,
        "protein_g": 2,
        "carbs_g": 24,
        "fat_g": 0,
        "sodium_mg": 50,
        "serving_size": "200ml",
        "origin": "국내산 케일",
        "score": 82
    },
    {
        "meal_id": "99",
        "name": "CJ 프레시웨이 그릭요거트",
        "brand": "CJ제일제당",
        "category": "유제품",
        "ingredients": ["그릭요거트", "꿀", "견과류"],
        "allergens": ["milk", "tree nuts"],
        "calories": 150,
        "protein_g": 10,
        "carbs_g": 18,
        "fat_g": 4,
        "sodium_mg": 70,
        "serving_size": "150g",
        "origin": "국내산 우유",
        "score": 85
    },
    {
        "meal_id": "100",
        "name": "빙그레 떠먹는 요플레",
        "brand": "빙그레",
        "category": "유제품",
        "ingredients": ["우유", "유산균", "과일"],
        "allergens": ["milk"],
        "calories": 95,
        "protein_g": 5,
        "carbs_g": 14,
        "fat_g": 2,
        "sodium_mg": 65,
        "serving_size": "120g",
        "origin": "국내산 우유",
        "score": 82
    }
]

# Generate the Python code
print("# 60 Additional Korean Meals (ID 41-100)")
print()

for meal in meals:
    print(f"        {{")
    print(f"            \"meal_id\": \"{meal['meal_id']}\",")
    print(f"            \"name\": \"{meal['name']}\",")
    print(f"            \"brand\": \"{meal['brand']}\",")
    print(f"            \"category\": \"{meal['category']}\",")
    print(f"            \"ingredients\": {meal['ingredients']},")
    print(f"            \"allergens\": {meal['allergens']},")
    print(f"            \"calories\": {meal['calories']},")
    print(f"            \"protein_g\": {meal['protein_g']},")
    print(f"            \"carbs_g\": {meal['carbs_g']},")
    print(f"            \"fat_g\": {meal['fat_g']},")
    print(f"            \"sodium_mg\": {meal['sodium_mg']},")
    print(f"            \"serving_size\": \"{meal['serving_size']}\",")
    print(f"            \"origin\": \"{meal['origin']}\",")
    print(f"            \"explanation_en\": f\"{meal['name']}. {meal['category']}. Good for {{request.health_goal}}.\",")
    print(f"            \"explanation_ko\": f\"{meal['name']}. {meal['category']}. {{request.health_goal}}에 좋습니다.\",")
    print(f"            \"score\": {meal['score']}")
    print(f"        }},")
