"""add identity to integer PKs

Revision ID: 8c5cecec27e8
Revises: 0ab3a5066185
Create Date: 2025-10-15 16:47:31.802139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5cecec27e8_add_identity_to_integer_pks'
down_revision: Union[str, Sequence[str], None] = '0ab3a5066185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE algo_feature_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE image_asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE meal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE meal_i18n ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE rating_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE recommendation_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE recommendation_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE user_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE user_health_measure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE user_interaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE user_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
    op.execute("ALTER TABLE user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")


def downgrade() -> None:
    """Downgrade schema."""op.execute("ALTER TABLE algo_feature_snapshot ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE image_asset ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE ingredient ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE meal ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE meal_i18n ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE rating_feedback ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE recommendation_item ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE recommendation_session ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE user_account ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE user_health_measure ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE user_interaction ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE user_preference ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE user_profile ALTER COLUMN id DROP IDENTITY IF EXISTS;")
