app:
  language: "en"  # 기본 언어 설정 ("en", "ko", "jp" 등)
  debug: true

model:
  name: "fitmeal-transformer"
  framework: "pytorch"
  weights_path: "./weights/fitmeal_model.pt"
  threshold: 0.7  # 식단 추천/성분 예측 확신도 임계값

ocr:
  engine: "clova"  # 사용할 OCR 모델: "clova", "donut", "pali-3" 등
  lang: "ko"       # OCR 인식 언어
  image_size: [1024, 1024]  # 입력 이미지 크기 리사이즈

allergy:
  detection_threshold: 0.6  # 이 확률 이상일 때 '경고'
  keywords:
    - 계란
    - 우유
    - 밀
    - 땅콩
    - 대두
    - 돼지고기
    - 복숭아
    - 토마토
    - 새우
    - 호두
    - 조개류
    - 메밀
    - 고등어
    - 게
    - 오징어
    - 굴
    - 전복
    - 홍합
    - 닭고기
    - 쇠고기
    - 아황산류
    - 이산화황

nutrition:
  default_values:   # 결측치 대체 기본값 (g 기준)
    protein: 0.0
    fat: 0.0
    carbs: 0.0
  kcal_formula: "4*protein + 9*fat + 4*carbs"

database:
  uri: "sqlite:///fitmealor.db"  # or your PostgreSQL/MySQL URI
  use_chroma: true
  chroma_collection: "fitmealor_nutrition_vectors"

output:
  result_card_limit: 10 # Top-10 출력
  show_allergy_warning: true
  show_macros: true
  enable_download: false

device:
  use_cuda: true

